[package]
name = "glimbot"
version = "0.1.0"
authors = ["Nicholas Samson <me@nicksamson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.11"
clap = "2.33.0"
serde = "1.0.104"
better-panic = "0.2.0"
regex = "1.3.4"
thiserror = "1.0.11"
once_cell = "1.3.1"
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.10"

[dependencies.serenity]
version = "0.8.0"

[dependencies.diesel]
version = "1.4.3"
features = ["sqlite"]